version: '3.8'
services:
  pokerbirds:
    container_name: pokerbirds_test
    image: pokerbirds_test
    restart: always
    build: .
    depends_on:
     - 'database'
    ports:
     - '80:3000'

  database:
    container_name: pokerbirds_database
    image: mongo:latest
    ports:
     - '27017:27017'