version: '3.8'
services:
  pokerbirds:
    container_name: pokerbirds
    image: pokerbirds
    restart: always
    build: .
    depends_on:
     - 'database'
    ports:
     - '3000:3000'

  database:
    image: mongo:latest
    ports:
     - '27017:27017'